// noinspection JSUnusedGlobalSymbols

export default {
    AmmoIcon: () => import('@/components/icons/AmmoIcon.vue'),
    AmmoReturnsIcon: () => import('@/components/icons/AmmoReturnsIcon.vue'),
    ArtifactIcon: () => import('@/components/icons/ArtifactIcon.vue'),
    AutoCloseHitIcon: () => import('@/components/icons/AutoCloseHitIcon.vue'),
    Blast2Icon: () => import('@/components/icons/Blast2Icon.vue'),
    BoomerangIcon: () => import('@/components/icons/BoomerangIcon.vue'),
    BreachIcon: () => import('@/components/icons/BreachIcon.vue'),
    Burst1Icon: () => import('@/components/icons/Burst1Icon.vue'),
    Burst2Icon: () => import('@/components/icons/Burst2Icon.vue'),
    CloseIcon: () => import('@/components/icons/CloseIcon.vue'),
    DeflectIcon: () => import('@/components/icons/DeflectIcon.vue'),
    DiscardIcon: () => import('@/components/icons/DiscardIcon.vue'),
    DysonIcon: () => import('@/components/icons/DysonIcon.vue'),
    DysonRangeIcon: () => import('@/components/icons/DysonRangeIcon.vue'),
    DysonThrowIcon: () => import('@/components/icons/DysonThrowIcon.vue'),
    EffortlessIcon: () => import('@/components/icons/EffortlessIcon.vue'),
    EffortlessReloadIcon: () =>
        import('@/components/icons/EffortlessReloadIcon.vue'),
    EventIcon: () => import('@/components/icons/EventIcon.vue'),
    ExplodeIcon: () => import('@/components/icons/ExplodeIcon.vue'),
    FadeToBlack3Icon: () => import('@/components/icons/FadeToBlack3Icon.vue'),
    FlipIcon: () => import('@/components/icons/FlipIcon.vue'),
    FreeCloseIcon: () => import('@/components/icons/FreeCloseIcon.vue'),
    FreezeIcon: () => import('@/components/icons/FreezeIcon.vue'),
    FullChargeIcon: () => import('@/components/icons/FullChargeIcon.vue'),
    GrenadeIcon: () => import('@/components/icons/GrenadeIcon.vue'),
    GrenadeLauncherIcon: () =>
        import('@/components/icons/GrenadeLauncherIcon.vue'),
    HeavyIcon: () => import('@/components/icons/HeavyIcon.vue'),
    IgnoreArmourIcon: () => import('@/components/icons/IgnoreArmourIcon.vue'),
    IgnoreShieldIcon: () => import('@/components/icons/IgnoreShieldIcon.vue'),
    InfiniteIcon: () => import('@/components/icons/InfiniteIcon.vue'),
    InfraLensIcon: () => import('@/components/icons/InfraLensIcon.vue'),
    KeyIcon: () => import('@/components/icons/KeyIcon.vue'),
    Manipulate3Icon: () => import('@/components/icons/Manipulate3Icon.vue'),
    MechIcon: () => import('@/components/icons/MechIcon.vue'),
    MineIcon: () => import('@/components/icons/MineIcon.vue'),
    MoveIcon: () => import('@/components/icons/MoveIcon.vue'),
    NaIcon: () => import('@/components/icons/NaIcon.vue'),
    NecroFlaskIcon: () => import('@/components/icons/NecroFlaskIcon.vue'),
    ObjectiveIcon: () => import('@/components/icons/ObjectiveIcon.vue'),
    PairsIcon: () => import('@/components/icons/PairsIcon.vue'),
    PhaseIcon: () => import('@/components/icons/PhaseIcon.vue'),
    PhysicalArmourIcon: () =>
        import('@/components/icons/PhysicalArmourIcon.vue'),
    RangeIcon: () => import('@/components/icons/RangeIcon.vue'),
    RareIcon: () => import('@/components/icons/RareIcon.vue'),
    ReliableIcon: () => import('@/components/icons/ReliableIcon.vue'),
    RepairIcon: () => import('@/components/icons/RepairIcon.vue'),
    ReRollIcon: () => import('@/components/icons/ReRollIcon.vue'),
    ReRollRangedIcon: () => import('@/components/icons/ReRollRangedIcon.vue'),
    ScatterIcon: () => import('@/components/icons/ScatterIcon.vue'),
    ScrambleIcon: () => import('@/components/icons/ScrambleIcon.vue'),
    SearchIcon: () => import('@/components/icons/SearchIcon.vue'),
    ShieldArmourIcon: () => import('@/components/icons/ShieldArmourIcon.vue'),
    SilentIcon: () => import('@/components/icons/SilentIcon.vue'),
    StimActionsIcon: () => import('@/components/icons/StimActionsIcon.vue'),
    StimHealIcon: () => import('@/components/icons/StimHealIcon.vue'),
    StimHealPlusIcon: () => import('@/components/icons/StimHealPlusIcon.vue'),
    StimSkillPlusIcon: () => import('@/components/icons/StimSkillPlusIcon.vue'),
    StimSkillIcon: () => import('@/components/icons/StimSkillIcon.vue'),
    SuperAmmoIcon: () => import('@/components/icons/SuperAmmoIcon.vue'),
    SuperReliableIcon: () => import('@/components/icons/SuperReliableIcon.vue'),
    SwapIcon: () => import('@/components/icons/SwapIcon.vue'),
    TargetLockIcon: () => import('@/components/icons/TargetLockIcon.vue'),
    TempArmourIcon: () => import('@/components/icons/TempArmourIcon.vue'),
    ThrowIcon: () => import('@/components/icons/ThrowIcon.vue'),
    TimewarpIcon: () => import('@/components/icons/TimewarpIcon.vue'),
    TrophyIcon: () => import('@/components/icons/TrophyIcon.vue'),
}
