// noinspection JSUnusedGlobalSymbols

export default {
    Action2Icon: () => import('@/components/icons/Action2Icon.vue'),
    Ammo7Icon: () => import('@/components/icons/Ammo7Icon.vue'),
    AmmoBoxIcon: () => import('@/components/icons/AmmoBoxIcon.vue'),
    AmmoD6Icon: () => import('@/components/icons/AmmoD6Icon.vue'),
    AmmoIcon: () => import('@/components/icons/AmmoIcon.vue'),
    AmmoReturnsIcon: () => import('@/components/icons/AmmoReturnsIcon.vue'),
    ArtifactIcon: () => import('@/components/icons/ArtifactIcon.vue'),
    AutoCloseHitIcon: () => import('@/components/icons/AutoCloseHitIcon.vue'),
    BeltIcon: () => import('@/components/icons/BeltIcon.vue'),
    Blast2Icon: () => import('@/components/icons/Blast2Icon.vue'),
    BackpackAllIcon: () => import('@/components/icons/BackpackAllIcon.vue'),
    BackpackNanoIcon: () => import('@/components/icons/BackpackNanoIcon.vue'),
    BlueArmourIcon: () => import('@/components/icons/BlueArmourIcon.vue'),
    BlueArmourRegenIcon: () =>
        import('@/components/icons/BlueArmourRegenIcon.vue'),
    BombIcon: () => import('@/components/icons/BombIcon.vue'),
    BoomerangIcon: () => import('@/components/icons/BoomerangIcon.vue'),
    BreachIcon: () => import('@/components/icons/BreachIcon.vue'),
    Burst1Icon: () => import('@/components/icons/Burst1Icon.vue'),
    Burst2Icon: () => import('@/components/icons/Burst2Icon.vue'),
    CloseIcon: () => import('@/components/icons/CloseIcon.vue'),
    DangerousIcon: () => import('@/components/icons/DangerousIcon.vue'),
    DataIcon: () => import('@/components/icons/DataIcon.vue'),
    DeflectIcon: () => import('@/components/icons/DeflectIcon.vue'),
    DiscardIcon: () => import('@/components/icons/DiscardIcon.vue'),
    DysonIcon: () => import('@/components/icons/DysonIcon.vue'),
    DysonRangeIcon: () => import('@/components/icons/DysonRangeIcon.vue'),
    DysonThrowIcon: () => import('@/components/icons/DysonThrowIcon.vue'),
    EffortlessArmourIcon: () =>
        import('@/components/icons/EffortlessArmourIcon.vue'),
    EffortlessIcon: () => import('@/components/icons/EffortlessIcon.vue'),
    EffortlessReloadIcon: () =>
        import('@/components/icons/EffortlessReloadIcon.vue'),
    EventIcon: () => import('@/components/icons/EventIcon.vue'),
    ExplodeIcon: () => import('@/components/icons/ExplodeIcon.vue'),
    FadeToBlack3Icon: () => import('@/components/icons/FadeToBlack3Icon.vue'),
    FearIcon: () => import('@/components/icons/FearIcon.vue'),
    FfIcon: () => import('@/components/icons/FfIcon.vue'),
    FireIcon: () => import('@/components/icons/FireIcon.vue'),
    FlipIcon: () => import('@/components/icons/FlipIcon.vue'),
    FreeCloseIcon: () => import('@/components/icons/FreeCloseIcon.vue'),
    FreezeIcon: () => import('@/components/icons/FreezeIcon.vue'),
    FuelIcon: () => import('@/components/icons/FuelIcon.vue'),
    FullChargeIcon: () => import('@/components/icons/FullChargeIcon.vue'),
    GearIcon: () => import('@/components/icons/GearIcon.vue'),
    GrenadeIcon: () => import('@/components/icons/GrenadeIcon.vue'),
    GrenadeLauncherIcon: () =>
        import('@/components/icons/GrenadeLauncherIcon.vue'),
    HeavyIcon: () => import('@/components/icons/HeavyIcon.vue'),
    HoverIcon: () => import('@/components/icons/HoverIcon.vue'),
    IgnoreArmourIcon: () => import('@/components/icons/IgnoreArmourIcon.vue'),
    IgnoreKnowledgeIcon: () =>
        import('@/components/icons/IgnoreKnowledgeIcon.vue'),
    IgnoreShieldIcon: () => import('@/components/icons/IgnoreShieldIcon.vue'),
    InfiniteIcon: () => import('@/components/icons/InfiniteIcon.vue'),
    InfraLensIcon: () => import('@/components/icons/InfraLensIcon.vue'),
    InterruptIcon: () => import('@/components/icons/InterruptIcon.vue'),
    KeyIcon: () => import('@/components/icons/KeyIcon.vue'),
    Manipulate3Icon: () => import('@/components/icons/Manipulate3Icon.vue'),
    MechIcon: () => import('@/components/icons/MechIcon.vue'),
    MineIcon: () => import('@/components/icons/MineIcon.vue'),
    MoveIcon: () => import('@/components/icons/MoveIcon.vue'),
    NaIcon: () => import('@/components/icons/NaIcon.vue'),
    NecroFlaskIcon: () => import('@/components/icons/NecroFlaskIcon.vue'),
    ObjectiveIcon: () => import('@/components/icons/ObjectiveIcon.vue'),
    PairsIcon: () => import('@/components/icons/PairsIcon.vue'),
    PhaseIcon: () => import('@/components/icons/PhaseIcon.vue'),
    PhysicalArmourIcon: () =>
        import('@/components/icons/PhysicalArmourIcon.vue'),
    RangeIcon: () => import('@/components/icons/RangeIcon.vue'),
    RareIcon: () => import('@/components/icons/RareIcon.vue'),
    ReliableIcon: () => import('@/components/icons/ReliableIcon.vue'),
    Repair2Icon: () => import('@/components/icons/Repair2Icon.vue'),
    RepairIcon: () => import('@/components/icons/RepairIcon.vue'),
    ReRollIcon: () => import('@/components/icons/ReRollIcon.vue'),
    ReRollRangedIcon: () => import('@/components/icons/ReRollRangedIcon.vue'),
    ScatterIcon: () => import('@/components/icons/ScatterIcon.vue'),
    ScrambleIcon: () => import('@/components/icons/ScrambleIcon.vue'),
    ScytheIcon: () => import('@/components/icons/ScytheIcon.vue'),
    SearchIcon: () => import('@/components/icons/SearchIcon.vue'),
    ShieldArmourIcon: () => import('@/components/icons/ShieldArmourIcon.vue'),
    SilentIcon: () => import('@/components/icons/SilentIcon.vue'),
    SpecialArmourIcon: () => import('@/components/icons/SpecialArmourIcon.vue'),
    StimCombatIcon: () => import('@/components/icons/StimCombatIcon.vue'),
    StimHealIcon: () => import('@/components/icons/StimHealIcon.vue'),
    StimHealPlusIcon: () => import('@/components/icons/StimHealPlusIcon.vue'),
    StimSkillIcon: () => import('@/components/icons/StimSkillIcon.vue'),
    StimSkillPlusIcon: () => import('@/components/icons/StimSkillPlusIcon.vue'),
    SuperAmmoIcon: () => import('@/components/icons/SuperAmmoIcon.vue'),
    SuperReliableIcon: () => import('@/components/icons/SuperReliableIcon.vue'),
    SupplyDropIcon: () => import('@/components/icons/SupplyDropIcon.vue'),
    SustainedFireIcon: () => import('@/components/icons/SustainedFireIcon.vue'),
    SwapIcon: () => import('@/components/icons/SwapIcon.vue'),
    TargetLockIcon: () => import('@/components/icons/TargetLockIcon.vue'),
    TempArmourIcon: () => import('@/components/icons/TempArmourIcon.vue'),
    ThrowIcon: () => import('@/components/icons/ThrowIcon.vue'),
    TimewarpIcon: () => import('@/components/icons/TimewarpIcon.vue'),
    ToxicIcon: () => import('@/components/icons/ToxicIcon.vue'),
    TripleChargeIcon: () => import('@/components/icons/TripleChargeIcon.vue'),
    TrophyIcon: () => import('@/components/icons/TrophyIcon.vue'),
    TrueBornIcon: () => import('@/components/icons/TrueBornIcon.vue'),
    WeaponMountIcon: () => import('@/components/icons/WeaponMountIcon.vue'),
}
