import { TokenType } from '@/tokens/types'

const tokens: TokenType[] = [
    {
        product: 'first-born',
        slug: 'port-engram',
        name: 'Port engram',
        color: 'green',
        size: 'sm',
        sell: 3,
        icons: ['effortless', 'flip'],
    },
    {
        product: 'first-born',
        slug: 'shield-engram',
        name: 'Shield engram',
        color: 'green',
        size: 'sm',
        sell: 3,
        icons: ['effortless', 'flip'],
        shield: [3, 2],
    },
    {
        product: 'first-born',
        slug: 'phase-engram',
        name: 'Phase engram',
        color: 'green',
        size: 'sm',
        sell: 5,
        phase: 1,
        icons: ['effortless', 'flip'],
    },
    {
        product: 'first-born',
        slug: 'liege-shard-6',
        name: 'Liege shard',
        color: 'green',
        size: 'sm',
        close: 3,
        throw: 3,
        sell: 6,
        icons: ['effortless', 're-roll'],
    },
    {
        product: 'first-born',
        slug: 'liege-shard-4',
        name: 'Liege shard',
        color: 'green',
        size: 'sm',
        close: 3,
        throw: 3,
        sell: 4,
        icons: ['effortless'],
    },
    {
        product: 'first-born',
        slug: 'dyson-spike',
        name: 'Dyson spike',
        color: 'green',
        size: 'sm',
        close: 3,
        throw: [6, 3, 2],
        range: 'm',
        sell: 8,
    },
    {
        product: 'first-born',
        slug: 'dyson-draw',
        name: 'Dyson draw',
        color: 'green',
        size: 'sm',
        sell: [5, 8],
        icons: ['dyson', 'dyson-throw'],
    },
    {
        product: 'first-born',
        slug: 'dyson-vent',
        name: 'Dyson vent',
        color: 'green',
        size: 'sm',
        sell: [5, 8],
        icons: ['dyson', 'dyson-range'],
    },
    {
        product: 'first-born',
        slug: 'phase-loop',
        name: 'Phase loop',
        color: 'green',
        size: 'sm',
        sell: [6, 12],
        throw: [3, 4],
        icons: ['boomerang'],
    },
    {
        product: 'first-born',
        slug: 'larva',
        name: 'Larva',
        color: 'green',
        size: 'sm',
        icons: ['flip', 'larva'],
    },
    {
        product: 'first-born',
        slug: 'fibril',
        name: 'Fibril',
        color: 'green',
        size: 'sm',
        sell: [3, 5, 8],
        icons: ['discard', 'repair'],
    },
    {
        product: 'first-born',
        slug: 'necro-flask',
        name: 'Necro flask',
        color: 'green',
        size: 'sm',
        sell: 5,
    },
    {
        product: 'first-born',
        slug: 'sypher-orb',
        name: 'Sypher orb',
        color: 'green',
        size: 'sm',
        sell: 2,
    },

    {
        product: 'first-born',
        slug: 'ecco-orb',
        name: 'Ecco orb',
        color: 'green',
        size: 'sm',
        sell: 7,
    },
    {
        product: 'first-born',
        slug: 'photon-shifter',
        name: 'Photon shifter',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'matter-shifter',
        name: 'Matter shifter',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'liege-ring-6',
        name: 'Liege ring',
        color: 'green',
        size: 'sm',
        sell: 6,
    },
    {
        product: 'first-born',
        slug: 'liege-ring-4',
        name: 'Liege ring',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'artifact',
        name: 'Artifact',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'quantum-lens',
        name: 'Quantum lens',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'artifact-4',
        name: 'Artifact',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'bracer',
        name: 'Bracer',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'shard-fins',
        name: 'Shard fins',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'raw-materials',
        name: 'Raw materials',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'liege-shard-5',
        name: 'Liege shard',
        color: 'green',
        size: 'sm',
    },
]

export default tokens
