import { TokenType } from '@/tokens/types'

const tokens: TokenType[] = [
    {
        product: 'first-born',
        slug: 'port-engram',
        name: 'Port engram',
        color: 'green',
        size: 'sm',
        sell: 3,
        icons: ['scatter', 'effortless', 'flip'],
    },
    {
        product: 'first-born',
        slug: 'shield-engram',
        name: 'Shield engram',
        color: 'green',
        size: 'sm',
        sell: 3,
        description: ['rotating'],
        icons: ['effortless', 'flip', 'physical_armour', 'discard'],
    },
    {
        product: 'first-born',
        slug: 'phase-engram',
        name: 'Phase engram',
        color: 'green',
        size: 'sm',
        sell: 5,
        phase: 1,
        icons: ['effortless', 'flip'],
    },
    {
        product: 'first-born',
        slug: 'liege-shard-6',
        name: 'Liege shard',
        color: 'green',
        size: 'sm',
        close: 3,
        throw: 3,
        sell: 6,
        icons: ['re-roll'],
    },
    {
        product: 'first-born',
        slug: 'liege-shard-4',
        name: 'Liege shard',
        color: 'green',
        size: 'sm',
        close: 3,
        throw: 3,
        sell: 4,
        icons: ['effortless'],
    },
    {
        product: 'first-born',
        slug: 'dyson-spike',
        name: 'Dyson spike',
        color: 'green',
        size: 'sm',
        close: 3,
        grenade: [6, 3, 2],
        range: 'm',
        sell: 8,
    },
    {
        product: 'first-born',
        slug: 'dyson-draw-5',
        name: 'Dyson draw',
        color: 'green',
        size: 'sm',
        sell: 8,
        dyson: 5,
        icons: ['dyson-throw'],
    },
    {
        product: 'first-born',
        slug: 'dyson-draw-3',
        name: 'Dyson draw',
        color: 'green',
        size: 'sm',
        sell: 5,
        dyson: 3,
        icons: ['dyson-throw'],
    },
    {
        product: 'first-born',
        slug: 'dyson-vent-5',
        name: 'Dyson vent',
        color: 'green',
        size: 'sm',
        sell: 8,
        dyson: 5,
        icons: ['dyson-range'],
    },
    {
        product: 'first-born',
        slug: 'dyson-vent-3',
        name: 'Dyson vent',
        color: 'green',
        size: 'sm',
        sell: 8,
        dyson: 3,
        icons: ['dyson-range'],
    },
    {
        product: 'first-born',
        slug: 'phase-loop-4',
        name: 'Phase loop',
        color: 'green',
        size: 'sm',
        sell: 12,
        throw: 4,
        icons: ['boomerang'],
    },
    {
        product: 'first-born',
        slug: 'phase-loop-3',
        name: 'Phase loop',
        color: 'green',
        size: 'sm',
        sell: 6,
        throw: 3,
        icons: ['boomerang'],
    },
    {
        product: 'first-born',
        slug: 'larva',
        name: 'Larva',
        color: 'green',
        size: 'sm',
        description: ['larva'],
        icons: ['flip'],
    },
    {
        product: 'first-born',
        slug: 'fibril',
        name: 'Fibril',
        color: 'green',
        size: 'sm',
        sell: [3, 5, 8],
        icons: ['repair', 'discard'],
    },
    {
        product: 'first-born',
        slug: 'necro-flask',
        name: 'Necro flask',
        color: 'green',
        size: 'sm',
        sell: 5,
        icons: ['necro-flask'],
    },
    {
        product: 'first-born',
        slug: 'sypher-orb',
        name: 'Sypher orb',
        color: 'green',
        size: 'sm',
        sell: 2,
        icons: ['effortless', 'event', 'discard'],
    },

    {
        product: 'first-born',
        slug: 'ecco-orb',
        name: 'Ecco orb',
        color: 'green',
        size: 'sm',
        sell: 7,
    },
    {
        product: 'first-born',
        slug: 'photon-shifter',
        name: 'Photon shifter',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'matter-shifter',
        name: 'Matter shifter',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'liege-ring-6',
        name: 'Liege ring',
        color: 'green',
        size: 'sm',
        sell: 6,
    },
    {
        product: 'first-born',
        slug: 'liege-ring-4',
        name: 'Liege ring',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'artifact',
        name: 'Artifact',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'quantum-lens',
        name: 'Quantum lens',
        color: 'green',
        size: 'sm',
        sell: 4,
    },
    {
        product: 'first-born',
        slug: 'artifact-4',
        name: 'Artifact',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'bracer',
        name: 'Bracer',
        color: 'green',
        size: 'sm',
        short: 2,
        medium: 3,
        icons: ['silent', 'infinite'],
    },
    {
        product: 'first-born',
        slug: 'shard-fin-8',
        name: 'Shard fins',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'shard-fin-4',
        name: 'Shard fins',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'raw-materials',
        name: 'Raw materials',
        color: 'green',
        size: 'sm',
    },
    {
        product: 'first-born',
        slug: 'liege-shard-5',
        name: 'Liege shard',
        color: 'green',
        size: 'sm',
        close: 3,
        throw: 3,
    },
    {
        product: 'first-born',
        slug: 'mining-drubber',
        name: 'Mining drubber',
        color: 'red',
        size: 'sm',
        icons: ['mine'],
    },
    {
        product: 'first-born',
        slug: 'combat-vest',
        name: 'Combat vest',
        color: 'yellow',
        size: 'sm',
        armour: 1,
    },
    {
        product: 'first-born',
        slug: 'combat-vest-shiny',
        name: 'Combat vest shiny',
        color: 'yellow',
        size: 'sm',
        armour: 1,
    },
    {
        product: 'first-born',
        slug: 'shield-belt',
        name: 'Shield belt',
        color: 'yellow',
        size: 'sm',
        shield: 1,
    },
    {
        product: 'first-born',
        slug: 'shield-belt-custom',
        name: 'Shield belt custom',
        color: 'yellow',
        size: 'sm',
        shield: 2,
    },
    {
        product: 'first-born',
        slug: 'neoflex-plate',
        name: 'Neoflex plate upgrade',
        color: 'yellow',
        size: 'sm',
        armour: 1,
        icons: ['mech'],
    },
    {
        product: 'first-born',
        slug: 'common-pistol',
        name: 'Common pistol',
        color: 'blue',
        size: 'sm',
        short: 1,
        medium: 1,
        icons: ['burst-1'],
    },
    {
        product: 'first-born',
        slug: 'military-pistol',
        name: 'Military pistol',
        color: 'blue',
        size: 'sm',
        short: 2,
        medium: 1,
        icons: ['burst-1'],
    },
    {
        product: 'first-born',
        slug: 'energy-pistol',
        name: 'Energy pistol',
        color: 'blue',
        size: 'sm',
        short: 2,
        medium: 2,
        icons: ['full-charge'],
    },
    {
        product: 'first-born',
        slug: 'machine-pistol',
        name: 'Machine pistol',
        color: 'blue',
        size: 'sm',
        short: 3,
        medium: 1,
    },
    {
        product: 'first-born',
        slug: 'officer-pistol',
        name: "Officer's pistol custom",
        color: 'blue',
        size: 'sm',
        short: 2,
        medium: 2,
        long: 1,
        icons: ['burst-1'],
    },
    {
        product: 'first-born',
        slug: 'burst-vest',
        name: 'Burst vest',
        color: 'yellow',
        size: 'sm',
        armour: 1,
        icons: ['effortless', 'flip'],
    },
    {
        product: 'first-born',
        slug: 'utility-knife',
        name: 'Utility knife',
        color: 'blue',
        size: 'sm',
        close: 1,
        throw: 1,
    },
    {
        product: 'first-born',
        slug: 'energy-combat-knife',
        name: 'Energy combat knife',
        color: 'blue',
        size: 'sm',
        close: 2,
        throw: 2,
    },
    {
        product: 'first-born',
        slug: 'short-sword-crafted',
        name: 'Short sword crafted',
        color: 'blue',
        size: 'sm',
        close: 2,
        heavy: 3,
        throw: 2,
    },
    {
        product: 'first-born',
        slug: 'outland-pistol',
        name: 'Outland pistol',
        color: 'blue',
        size: 'sm',
        short: 1,
    },
    {
        product: 'first-born',
        slug: 'hunter-trophy',
        name: "Hunter's trophy objective",
        color: 'brown',
        size: 'sm',
        icons: ['trophy'],
    },
    {
        product: 'first-born',
        slug: 'magnum-custom',
        name: 'Magnum custom',
        color: 'blue',
        size: 'sm',
        short: 3,
        medium: 2,
    },
    {
        product: 'first-born',
        slug: 'military-twin',
        name: 'Military twin',
        color: 'blue',
        size: 'sm',
        short: 2,
        medium: 2,
        icons: ['burst-1'],
    },
    {
        product: 'first-born',
        slug: 'quell-riposte',
        name: "Quell's riposte",
        color: 'blue',
        size: 'sm',
        short: 2,
        close: 3,
        icons: ['burst-1'],
    },
    {
        product: 'first-born',
        slug: 'havoc-custom',
        name: 'Havoc custom',
        color: 'blue',
        size: 'sm',
        short: 3,
        icons: ['re-roll'],
    },
]

export default tokens
