import { TokenType } from '../types'

const tokens: TokenType[] = [
    {
        product: 'line-of-fire',
        slug: 'burst-vest',
        name: 'Burst vest',
        color: 'white',
        size: 'sm',
        armour: 1,
        description: ['supply-drop', 'rotating'],
        icons: ['effortless', 'flip', 'discard'],
        sell: 4,
    },
    {
        product: 'line-of-fire',
        slug: 'hi-ex',
        name: 'Hi-ex explosive',
        color: 'white',
        size: 'sm',
        explode: [6, 5, 4, 3],
        description: ['supply-drop'],
        icons: ['reliable', 'bomb'],
        sell: 2,
    },
    {
        product: 'line-of-fire',
        slug: 'medi-pack',
        name: 'Medi pack',
        color: 'white',
        size: 'sm',
        description: ['supply-drop'],
        heal: 4,
    },
    {
        product: 'line-of-fire',
        slug: 'n-action',
        name: 'Stim action',
        color: 'white',
        size: 'nano',
        action: 2,
        description: ['supply-drop'],
        icons: ['effortless', 'discard'],
    },
    {
        product: 'line-of-fire',
        slug: 'n-heal',
        name: 'Stim heal',
        color: 'white',
        size: 'nano',
        heal: 2,
        description: ['supply-drop'],
        icons: ['effortless', 'discard'],
    },
    {
        product: 'line-of-fire',
        slug: 'n-skill',
        name: 'Stim skill',
        color: 'white',
        size: 'nano',
        skill: 2,
        description: ['supply-drop'],
        icons: ['effortless', 'discard'],
    },
    {
        product: 'line-of-fire',
        slug: 'tactical-military-pistol',
        name: 'Tactical military pistol',
        color: 'white',
        size: 'sm',
        short: 3,
        medium: 1,
        description: ['supply-drop'],
        icons: ['burst-1'],
        sell: 3,
    },
    {
        product: 'line-of-fire',
        slug: 'tech-pack',
        name: 'Tech pack',
        color: 'white',
        size: 'sm',
        description: ['supply-drop'],
        icons: ['repair'],
        sell: 1,
    },
    {
        product: 'line-of-fire',
        slug: 'w-ammo',
        name: 'Ammo',
        color: 'white',
        size: 'nano',
        description: ['supply-drop'],
        icons: ['ammo', 'discard'],
        sell: 1,
    },
    {
        product: 'line-of-fire',
        slug: 'w-mine',
        name: 'Grenade',
        color: 'white',
        size: 'nano',
        description: ['supply-drop'],
        grenade: [5, 3, 2],
        icons: ['discard'],
        sell: 2,
    },
    {
        product: 'line-of-fire',
        slug: 'ws-ammo',
        name: 'Accelerant ammo',
        color: 'white',
        size: 'nano',
        description: ['supply-drop'],
        icons: ['super-ammo', 'discard'],
        sell: 1,
    },
]
export default tokens
