import { TokenType } from '../types'

const tokens: TokenType[] = [
    {
        product: 'rysa',
        slug: 'dysonfire-shard-sword',
        name: 'Dysonfire shard sword',
        color: 'blue',
        size: 'md',
        close: 2,
        icons: ['fire'],
        sell: 18,
        buy: 0,
        crystals: ['orange'],
    },
    {
        product: 'rysa',
        slug: 'fibril-2',
        name: 'Fibril 2',
        color: 'green',
        size: 'sm',
        icons: ['repair', 'discard'],
        sell: 5,
    },
    {
        product: 'rysa',
        slug: 'hazard-pistol',
        name: 'Hazard pistol',
        color: 'blue',
        size: 'sm',
        short: 2,
        icons: ['toxic'],
        sell: 18,
        buy: 18,
        crystals: ['orange', 'orange'],
    },
    {
        product: 'rysa',
        slug: 'liege-shard-eff',
        name: 'Liege shard eff',
        color: 'green',
        size: 'sm',
        short: 3,
        throw: 3,
        icons: ['effortless'],
        sell: 4,
    },
    {
        product: 'rysa',
        slug: 'n-flask',
        name: 'Heal flask',
        color: 'green',
        size: 'nano',
        heal: 3,
        icons: ['discard'],
        sell: 3,
    },
    {
        product: 'rysa',
        slug: 'n-freeze',
        name: 'Freeze bomb',
        color: 'green',
        size: 'nano',
        freeze: [2, 2],
        sell: 4,
    },
    {
        product: 'rysa',
        slug: 'n-shard-blue',
        name: 'Blue shard',
        color: 'green',
        size: 'nano',
        throw: 3,
        icons: ['effortless'],
        sell: 2,
    },
    {
        product: 'rysa',
        slug: 'necro-flask',
        name: 'Necro flask',
        color: 'green',
        size: 'sm',
        icons: ['necro-flask'],
        sell: 5,
    },
    {
        product: 'rysa',
        slug: 'quantum-lens',
        name: 'Quantum lens',
        color: 'green',
        size: 'sm',
        range: 'm',
        icons: ['infra-lens', 'effortless', 'flip'],
        sell: 5,
    },
    {
        product: 'rysa',
        slug: 'raw-minerals',
        name: 'Raw minerals',
        color: 'green',
        size: 'sm',
        description: ['mineral'],
        sell: 5,
        crystals: ['green', 'purple'],
    },
    {
        product: 'rysa',
        slug: 'shield-engram-armour',
        name: 'Shield engram armour',
        color: 'green',
        size: 'sm',
        shield: 2,
        icons: ['flip'],
        sell: 5,
    },
    {
        product: 'rysa',
        slug: 'sypher-orb',
        name: 'Sypher orb',
        color: 'green',
        size: 'sm',
        icons: ['effortless', 'discard', 'event'],
        sell: 2,
    },
    {
        product: 'rysa',
        slug: 'toxic-lash-whip',
        name: 'Toxic lash whip',
        color: 'blue',
        size: 'md',
        close: 2,
        icons: ['toxic', 'scythe'],
        crystals: ['purple'],
        sell: 21,
        buy: 0,
    },
]
export default tokens
