import { TokenType } from '@/tokens/types'

const tokens: TokenType[] = [
    {
        product: 'wanted',
        slug: 'ammo',
        name: 'Ammo',
        color: 'orange',
        size: 'nano',
        buy: 4,
        sell: 2,
        icons: ['ammo', 'discard'],
    },
    {
        product: 'wanted',
        slug: 'binder-cuffs-energy-2',
        name: 'Binder cuffs energy',
        color: 'orange',
        size: 'sm',
        icons: ['cuffs'],
        buy: 7,
        sell: 4,
    },
    {
        product: 'wanted',
        slug: 'binder-cuffs-energy-3',
        name: 'Binder cuffs energy',
        color: 'orange',
        size: 'sm',
        icons: ['cuffs'],
        buy: 11,
        sell: 7,
    },
    {
        product: 'wanted',
        slug: 'combat-stim',
        name: 'Combat stim',
        color: 'orange',
        size: 'nano',
        action: 2,
        icons: ['effortless', 'discard'],
        buy: 3,
        sell: 1,
    },
    {
        product: 'wanted',
        slug: 'flame-fuel',
        name: 'Flame fuel',
        color: 'orange',
        size: 'sm',
        description: ['flame-fuel'],
        icons: ['fire', 'discard'],
        buy: 7,
        sell: 4,
    },
    {
        product: 'wanted',
        slug: 'flame-thrower',
        name: 'Flame thrower',
        color: 'blue',
        size: 'lg',
        description: ['flame-fuel'],
        icons: ['fire'],
        buy: 21,
        sell: 17,
    },
    {
        product: 'wanted',
        slug: 'grenade',
        name: 'Grenade',
        color: 'blue',
        size: 'nano',
        grenade: [4, 3, 1],
        icons: ['discard'],
        buy: 5,
        sell: 4,
    },
    {
        product: 'wanted',
        slug: 'heal-stim',
        name: 'Heal stim',
        color: 'orange',
        size: 'nano',
        heal: 2,
        icons: ['effortless', 'discard'],
        buy: 2,
        sell: 1,
    },
    {
        product: 'wanted',
        slug: 'magnum-pistol-custom',
        name: 'Magnum pistol custom',
        color: 'blue',
        size: 'sm',
        short: 3,
        medium: 3,
        icons: ['re-roll'],
        buy: 24,
        sell: 18,
    },
    {
        product: 'wanted',
        slug: 'multi-pistol',
        name: 'Multi pistol',
        color: 'blue',
        size: 'sm',
        short: 3,
        icons: ['burst-1', 'sustained-fire'],
        buy: 21,
        sell: 13,
    },
    {
        product: 'wanted',
        slug: 'objective',
        name: 'Objective',
        color: 'green',
        size: 'nano',
        icons: ['objective'],
    },
    {
        product: 'wanted',
        slug: 'poison-throw',
        name: 'Poison throw',
        color: 'blue',
        size: 'nano',
        throw: 2,
        icons: ['toxic', 'effortless'],
        buy: 8,
        sell: 4,
    },
    {
        product: 'wanted',
        slug: 'ranged-re-roll',
        name: 'Ranged re-roll',
        color: 'orange',
        size: 'nano',
        icons: ['re-roll-ranged'],
        buy: 18,
        sell: 11,
    },
    {
        product: 'wanted',
        slug: 'rocket-boots',
        name: 'Rocket boots',
        color: 'yellow',
        size: 'sm',
        scramble: [5, 5],
        icons: ['armour-re-roll'],
        buy: 24,
        sell: 18,
    },
    {
        product: 'wanted',
        slug: 'skill-stim',
        name: 'Skill stim',
        color: 'orange',
        size: 'nano',
        skill: 2,
        icons: ['effortless', 'discard'],
        buy: 4,
        sell: 1,
    },
    {
        product: 'wanted',
        slug: 'stun-baton-energy',
        name: 'Stun baton energy',
        color: 'blue',
        size: 'sm',
        close: 2,
        icons: ['stun'],
        buy: 7,
        sell: 4,
    },
    {
        product: 'wanted',
        slug: 'stun-pistol-energy',
        name: 'Stun pistol energy',
        color: 'blue',
        size: 'sm',
        short: 2,
        icons: ['stun'],
        buy: 14,
        sell: 8,
    },
    {
        product: 'wanted',
        slug: 'target-laser',
        name: 'Target laser',
        color: 'orange',
        size: 'nano',
        icons: ['target-lock'],
        buy: 15,
        sell: 8,
    },
    {
        product: 'wanted',
        slug: 'throw',
        name: 'Throwing knife',
        color: 'blue',
        size: 'nano',
        throw: 2,
        icons: ['effortless'],
        buy: 1,
        sell: 0,
    },
    {
        product: 'wanted',
        slug: 'yellow-grenade',
        name: 'Yellow nade',
        color: 'blue',
        size: 'nano',
        icons: ['discard'],
        grenade: [5, 3, 2],
        buy: 6,
        sell: 5,
    },
]
export default tokens
