import { TokenType } from '@/tokens/types'

const tokens: TokenType[] = [
    {
        product: 'yamato',
        slug: 'common-pistol',
        name: 'Common pistol',
        color: 'blue',
        size: 'sm',
        short: 1,
        medium: 1,
        icons: ['burst-1'],
        buy: 3,
        sell: 1,
    },
    {
        product: 'yamato',
        slug: 'empathic-cuffs',
        name: 'Empathic cuffs',
        color: 'orange',
        size: 'sm',
        icons: ['impervious-1', 'rare'],
        sell: 8,
    },
    {
        product: 'yamato',
        slug: 'knife',
        name: 'Knife',
        color: 'blue',
        size: 'sm',
        close: 1,
        buy: 0,
        sell: 0,
    },
    {
        product: 'yamato',
        slug: 'machine-pistol',
        name: 'Machine pistol',
        color: 'blue',
        size: 'sm',
        short: 3,
        medium: 1,
        buy: 12,
        sell: 6,
    },
    {
        product: 'yamato',
        slug: 'merg-plating',
        name: 'Merg plating',
        color: 'yellow',
        size: 'sm',
        description: ['merg'],
        armour: 2,
        buy: 30,
        sell: 18,
    },
    {
        product: 'yamato',
        slug: 'military-coat',
        name: 'Military coat',
        color: 'yellow',
        size: 'sm',
        armour: 1,
        shield: 2,
        close: 2,
        icons: ['flip', 'rare'],
    },
    {
        product: 'yamato',
        slug: 'military-pistol',
        name: 'Military pistol',
        color: 'blue',
        size: 'sm',
        short: 2,
        medium: 1,
        icons: ['reliable'],
        buy: 8,
        sell: 4,
    },
    {
        product: 'yamato',
        slug: 'n-ammo',
        name: 'Ammo mag',
        color: 'orange',
        size: 'sm',
        icons: ['ammo-7', 'discard'],
        buy: 2,
        sell: 1,
    },
    {
        product: 'yamato',
        slug: 'storm-bracers',
        name: 'Storm bracers',
        color: 'blue',
        size: 'lg',
        close: 4,
        description: ['merg'],
        icons: ['rare'],
        sell: 8,
    },
]
export default tokens
